# Generated by Django 4.2.6 on 2023-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='')),
                ('job', models.CharField(max_length=150)),
            ],
        ),
    ]
