# Generated by Django 4.2.6 on 2023-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_about_contactinfo_education_experience_fact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='is_freelance',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
