# Generated by Django 4.2.6 on 2023-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_alter_about_is_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='happy_clients',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='hard_workers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='hours_of_support',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='projects',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Design', 'Design'), ('Digital', 'Digital'), ('Graphics', 'Graphics')], max_length=20, null=True),
        ),
    ]
