# Generated by Django 4.2.6 on 2023-11-03 18:02

from django.db import migrations, models
import portapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_social_media_links_github_alter_about_is_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=portapp.models.upload_to_portfolio_images),
        ),
    ]
